---
- name: Install tomcat9068 on oel7 instance
  hosts: all
  become: yes
  vars:
    mysecret: TanGo#12+1
    mysql_url: 8.0.31
    java_url: zulu11.60.19-ca-jdk11.0.17-linux_x64
    tomcat_url: splashbi-apache-tomcat-9.0.70
    user_name: splashbi
    user_group: splashbi
    mysql_new_password: Welcome#$4321
  tasks:
    - name : create a directory for softwares
      ansible.builtin.file:      
        path: /home/{{ user_name }}/tomcat_test
        state: directory
        owner: '{{ user_name }}'
        group: '{{ user_group }}'
    - name: Update the yum repo
      ansible.builtin.yum:
        update_cache: yes
    - name: Start MySQL Server
      ansible.builtin.service:
        name: mysqld
        state: started
    - name: Get the temporary password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    - name: 1st grant
      ansible.builtin.command: mysql --user root --password={{ mysql_new_password }} --execute="CREATE USER 'root'@'%' IDENTIFIED BY 'Welcome#$4321';"
    - name: 2nd grant
      ansible.builtin.command: mysql --user root --password={{ mysql_new_password }} --connect-expired-password --execute="GRANT ALL PRIVILEGES ON . TO 'root'@'%';"
    - name: 3rd grant
      ansible.builtin.command: mysql --user root --password={{ mysql_new_password }} --connect-expired-password --execute="GRANT ALL PRIVILEGES ON . TO 'root'@'%' WITH GRANT OPTION;"
    - name: 3rd grant
      ansible.builtin.command: mysql --user root --password={{ mysql_new_password }} --connect-expired-password --execute="GRANT ALL PRIVILEGES ON . TO 'root'@'localhost' WITH GRANT OPTION;"

