---
- name: Install tomcat9068 on oel7 instance
  hosts: all
  become: yes
  vars:
    mysecret: TanGo#12+1
    mysql_url: 8.0.31
    java_url: zulu11.60.19-ca-jdk11.0.17-linux_x64
    tomcat_url: splashbi-apache-tomcat-9.0.70
    user_name: splashbi
    user_group: splashbi
    mysql_new_password: Welcome#$4321
  tasks:
    - name: Update the yum repo
      ansible.builtin.yum:
        update_cache: yes
        state: present
    - name: Get the temporary password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    - name: update expired root user password
      ansible.builtin.command: mysql --user root --password={{ result.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_new_password }}';"
    - name: copy my.cnf
      ansible.builtin.copy:
        src: /u01/AnsibleTest/my.cnf
        dest: /etc/my.cnf
        mode: 0644
    - name: Select query to db acme with positional arguments
      community.mysql.mysql_query:
        login_host: 192.168.4.48
        login_user: root
        login_password: Welcome#$4321
        login_port: 3306
        query:
          - CREATE USER 'root'@'%' IDENTIFIED BY 'Welcome#$4321';
          - GRANT ALL PRIVILEGES ON . TO 'root'@'%';
