---
- name: Install tomcat9068 on oel7 instance
  hosts: all
  become: yes
  vars:
    mysecret: TanGo#12+1
    mysql_url: 8.0.31
    java_url: zulu11.60.19-ca-jdk11.0.17-linux_x64
    tomcat_url: splashbi-apache-tomcat-9.0.70
    user_name: splashbi
    user_group: splashbi
    mysql_new_password: Welcome#$4321
  tasks:
    - name : create a directory for softwares
      ansible.builtin.file:      
        path: /home/{{ user_name }}/tomcat_test
        state: directory
        owner: '{{ user_name }}'
        group: '{{ user_group }}'
    - name: Update the yum repo
      ansible.builtin.yum:
        update_cache: yes
    - name: Start MySQL Server
      ansible.builtin.service:
        name: mysqld
        state: started
    - name: Get the temporary password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    - name: Store temporary password into mysql root password
      ansible.builtin.set_fact:
        mysql_root_pw: result.stdout
    - name: use mysql_secure_installation for Fresh MySQL Installation
      community.mysql.mysql_user:
        name: root
        host: 192.168.4.48
        password: '{{ mysql_new_password }}'
        check_implicit_admin: yes
        login_user: root
        login_password: '{{ mysql_root_pw }}'
        state: present
