---
- name: Install tomcat9068 on oel7 instance
  hosts: all
  become: yes
  vars:
    mysecret: TanGo#12+1
    java_url: zulu11.60.19-ca-jdk11.0.17-linux_x64
    tomcat_url: splashbi-apache-tomcat-9.0.70
  tasks:
    - name: download tomcat software from artifactory
      ansible.builtin.get_url:
        url: http://192.168.4.252:8081/artifactory/Software/Linux-software/{{ tomcat_url }}.zip
        dest: /u01/AnsibleTest
        username: admin
        password: '{{ mysecret }}'
    - name: download java software from artifactory
      ansible.builtin.get_url:
        url: http://192.168.4.252:8081/artifactory/Software/Linux-software/{{ java_url }}.zip
        dest: /u01/AnsibleTest
        username: admin
        password: '{{ mysecret }}'
    - name: unzip java file
      ansible.builtin.unarchive:
        src: /u01/AnsibleTest/{{ java_url }}.zip
        dest: /u01/AnsibleTest
        remote_src: yes
    - name: unzip tomcat file
      ansible.builtin.unarchive:
        src: /u01/AnsibleTest/{{ tomcat_url }}.zip
        dest: /u01/AnsibleTest
        remote_src: yes
    - name: permissions changing for java 
      ansible.builtin.file:
        path: /u01/AnsibleTest/{{ java_url }}
        state: directory
        recurse: yes
        owner: splashbi
        group: splashbi
    - name: permissions tomcat changing
      ansible.builtin.file:
        path: /u01/AnsibleTest/{{ tomcat_url }}
        state: directory
        recurse: yes
        owner: splashbi
        group: splashbi
    - name: "Set bin/*.sh permissions to allow execution"
      ansible.builtin.command:   
        cmd: find {{ tomcat_url }}/bin -type f -name "*.sh" -exec chmod -c 777 {} \;
 

    
