---
 - name: TO install Oracle Database
   hosts: all
   become: yes
   tasks:
     - name: Insert host entry in /etc/hosts
       lineinfile:
         path: /etc/hosts
         line: '192.168.8.211 splashfin003-idc888.splashbi.com splashfin003-idc888'
         state: present  # Ensure the line is present in the file
         become: yes
     - name: Restart network service
       service:
         name: network
         state: restarted
     - name: Install oracle-database-preinstall-19c 
       ansible.builtin.yum: 
         name: oracle-database-preinstall-19c
         update_cache: yes
         state: present
